-- Users table
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    role VARCHAR(50) NOT NULL,
    reports_to_manager_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    hire_date DATE,
    department VARCHAR(100),
    job_title VARCHAR(100),
    CONSTRAINT fk_users_manager FOREIGN KEY (reports_to_manager_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Clients table
CREATE TABLE clients (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    contact_email VARCHAR(255),
    address TEXT
);

-- Projects table
CREATE TABLE projects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    client_id INT NOT NULL,
    default_billable_rate NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'active',
    CONSTRAINT fk_projects_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- Project assignments table
CREATE TABLE project_assignments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    project_id INT NOT NULL,
    UNIQUE(user_id, project_id),
    CONSTRAINT fk_pa_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_pa_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- Timesheets table
CREATE TABLE timesheets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    week_start_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    submitted_at TIMESTAMP,
    approved_at TIMESTAMP,
    rejection_comments TEXT,
    UNIQUE(user_id, week_start_date),
    CONSTRAINT fk_timesheets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Time entries table
CREATE TABLE time_entries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timesheet_id INT NOT NULL,
    project_id INT,
    entry_date DATE NOT NULL,
    hours NUMERIC(4, 2) NOT NULL,
    task_type VARCHAR(20) NOT NULL,
    notes TEXT,
    CONSTRAINT fk_te_timesheet FOREIGN KEY (timesheet_id) REFERENCES timesheets(id) ON DELETE CASCADE,
    CONSTRAINT fk_te_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);

-- Invoices table
CREATE TABLE invoices (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    total_amount NUMERIC(10, 2) NOT NULL,
    amount_paid NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoices_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT
);

-- Invoice line items table
CREATE TABLE invoice_line_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INT NOT NULL,
    project_id INT,
    user_id INT,
    description TEXT,
    hours NUMERIC(10, 2) NOT NULL,
    rate NUMERIC(10, 2) NOT NULL,
    line_total NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_ili_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_ili_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_ili_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Payments table
CREATE TABLE payments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INT NOT NULL,
    payment_date DATE NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    method VARCHAR(50),
    notes TEXT,
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_manager ON users(reports_to_manager_id);
CREATE INDEX idx_projects_client ON projects(client_id);
CREATE INDEX idx_timesheets_user_week ON timesheets(user_id, week_start_date);
CREATE INDEX idx_timesheets_status ON timesheets(status);
CREATE INDEX idx_time_entries_timesheet ON time_entries(timesheet_id);
CREATE INDEX idx_time_entries_project ON time_entries(project_id);
CREATE INDEX idx_invoices_client ON invoices(client_id);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE INDEX idx_invoice_line_items_invoice ON invoice_line_items(invoice_id);
CREATE INDEX idx_payments_invoice ON payments(invoice_id);

